-- =====================================================
-- NUCLEAR RESET - Disable ALL RLS, Clean All Data
-- =====================================================

-- STEP 1: DISABLE RLS ON ALL TABLES
ALTER TABLE companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE sms_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_commissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE auth_challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_communication DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_rating_tokens DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE customer_blacklist DISABLE ROW LEVEL SECURITY;
ALTER TABLE employee_availability DISABLE ROW LEVEL SECURITY;
ALTER TABLE equipment_checklist_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE geofences DISABLE ROW LEVEL SECURITY;
ALTER TABLE google_review_bonuses DISABLE ROW LEVEL SECURITY;
ALTER TABLE gps_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE idempotency_keys DISABLE ROW LEVEL SECURITY;
ALTER TABLE incidents DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_photos DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_quality_issues DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_rework DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_upsells DISABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard DISABLE ROW LEVEL SECURITY;
ALTER TABLE loyalty_points DISABLE ROW LEVEL SECURITY;
ALTER TABLE loyalty_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_statements DISABLE ROW LEVEL SECURITY;
ALTER TABLE referrals DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales_territories DISABLE ROW LEVEL SECURITY;
ALTER TABLE shift_checklists DISABLE ROW LEVEL SECURITY;
ALTER TABLE technician_location_daily DISABLE ROW LEVEL SECURITY;
ALTER TABLE termination_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE upsell_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_audit_log DISABLE ROW LEVEL SECURITY;

-- STEP 2: DROP ALL FUNCTIONS
DROP FUNCTION IF EXISTS public.get_my_company_id() CASCADE;
DROP FUNCTION IF EXISTS public.get_my_role() CASCADE;
DROP FUNCTION IF EXISTS public.get_user_company_id() CASCADE;
DROP FUNCTION IF EXISTS public.get_user_role() CASCADE;

-- STEP 3: TRUNCATE ALL DATA (but keep schemas)
TRUNCATE TABLE user_audit_log CASCADE;
TRUNCATE TABLE user_sessions CASCADE;
TRUNCATE TABLE auth_challenges CASCADE;
TRUNCATE TABLE termination_records CASCADE;
TRUNCATE TABLE payroll_statements CASCADE;
TRUNCATE TABLE onboarding_progress CASCADE;
TRUNCATE TABLE notifications CASCADE;
TRUNCATE TABLE loyalty_transactions CASCADE;
TRUNCATE TABLE loyalty_points CASCADE;
TRUNCATE TABLE leaderboard CASCADE;
TRUNCATE TABLE leads CASCADE;
TRUNCATE TABLE job_upsells CASCADE;
TRUNCATE TABLE upsell_items CASCADE;
TRUNCATE TABLE job_rework CASCADE;
TRUNCATE TABLE job_quality_issues CASCADE;
TRUNCATE TABLE job_photos CASCADE;
TRUNCATE TABLE job_history CASCADE;
TRUNCATE TABLE job_assignments CASCADE;
TRUNCATE TABLE invoices CASCADE;
TRUNCATE TABLE incidents CASCADE;
TRUNCATE TABLE idempotency_keys CASCADE;
TRUNCATE TABLE gps_locations CASCADE;
TRUNCATE TABLE google_review_bonuses CASCADE;
TRUNCATE TABLE geofences CASCADE;
TRUNCATE TABLE equipment_checklist_templates CASCADE;
TRUNCATE TABLE employee_commissions CASCADE;
TRUNCATE TABLE employee_availability CASCADE;
TRUNCATE TABLE customer_rating_tokens CASCADE;
TRUNCATE TABLE customer_ratings CASCADE;
TRUNCATE TABLE customer_subscriptions CASCADE;
TRUNCATE TABLE customer_communication CASCADE;
TRUNCATE TABLE customer_blacklist CASCADE;
TRUNCATE TABLE referrals CASCADE;
TRUNCATE TABLE sms_messages CASCADE;
TRUNCATE TABLE shift_checklists CASCADE;
TRUNCATE TABLE sales_territories CASCADE;
TRUNCATE TABLE technician_location_daily CASCADE;
TRUNCATE TABLE jobs CASCADE;
TRUNCATE TABLE customers CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE companies CASCADE;

-- DONE
-- RLS is now DISABLED on all tables
-- All data is DELETED
-- Ready for fresh seed
